[tool.poetry]
name = "gui-python-gtk"
version = "0.1.0"
description = "Criando interfaces gráficas com Python e GTK."
authors = ["natorsc <natorsc@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
PyGObject = "^3.40.1"

[tool.poetry.dev-dependencies]
pylint = "^2.9.6"
autopep8 = "^1.5.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
