[tool.poetry]
name = "gui-python-gtk"
version = "0.1.0"
description = "Criando interfaces gráficas com Python e GTK."
authors = ["natorsc <natorsc@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9 || ^3.10"
PyGObject = "^3.42.0"

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
autopep8 = "^1.5.7"
PyGObject-stubs = "^0.0.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
